import "~/styles/globals.css";

import type { Metadata } from "next";
import Script from "next/script";
import GARouteTracker from "~/components/GARouteTracker";
import { Geist } from "next/font/google";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
	title: "Ekstra",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	const gaId = process.env.NEXT_PUBLIC_GA_ID;
	return (
		<html lang="en" className={`${geist.variable}`}>
        <head>
          {/* Google Analytics */}
          {gaId ? (
            <>
              <Script
                src={`https://www.googletagmanager.com/gtag/js?id=${gaId}`}
                strategy="afterInteractive"
              />
              <Script id="ga-init" strategy="afterInteractive">
                {`
                  window.dataLayer = window.dataLayer || [];
                  function gtag(){dataLayer.push(arguments);} 
                  gtag('js', new Date());
                  gtag('config', '${gaId}');
                `}
              </Script>
            </>
          ) : null}
        </head>
        <body>
          <SessionProvider>
            {children}
          </SessionProvider>
          {gaId ? <GARouteTracker /> : null}
        </body>
		</html>
	);
}
