import "~/styles/globals.css";
import type { Metadata } from "next";
import Script from "next/script";
import { Geist } from "next/font/google";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Ekstra",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({ subsets: ["latin"], variable: "--font-geist-sans" });

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={geist.variable}>
      <body>

        <>
          <Script id="monitoring-tag" strategy="beforeInteractive" type="text/javascript">
            {`
              (function(w,d,u,f){
                if (w[f]) return;
                w[f] = true;
                var s = d.createElement('script');
                s.async = true;
                s.src = u;
                d.getElementsByTagName('head')[0].appendChild(s);
              })(window, document, 'https://monitoring.supersmartsystem.com/beacon/rum.js?appKey=75c54110-2d62-4fd2-83b7-4fe06c160a9e', 'mtag');
            `}
          </Script>
        </>

        <SessionProvider>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
