import "~/styles/globals.css";
import type { Metadata } from "next";
import Script from "next/script";
import { Geist } from "next/font/google";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Ekstra",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({ subsets: ["latin"], variable: "--font-geist-sans" });

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const gaId = process.env.NEXT_PUBLIC_GA_ID; // e.g. G-XXXXXXX

  return (
    <html lang="en" className={geist.variable}>
      <body>

        <>
          <Script
            id="gtag-src"
            src={`https://www.googletagmanager.com/gtag/js?id=${gaId}`}
            strategy="beforeInteractive" // loads in <head>
          />
          <Script id="ga-init" strategy="beforeInteractive">
            {`
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);} 
              gtag('js', new Date());
              gtag('config', '${gaId}'); // keep auto page_view
            `}
          </Script>
          <Script id="network-script" strategy="afterInteractive">
            {`
              (() => {
                const SITE_KEY = '${process.env.NEXT_PUBLIC_NETWORK_SITE_KEY ?? "SITE_PUBLIC_KEY"}';
                const payload = { site_key: SITE_KEY, ref: document.referrer || null };
                const body = JSON.stringify(document);
                console.log('[network-script] Sending traffic payload:', payload);
                try {
                  navigator.sendBeacon('http://103.103.23.202/api/trafficData', new Blob([body], { type: 'application/json' }));
                } catch (err) {
                  console.log('[network-script] sendBeacon error:', err);
                }
              })();
            `}
          </Script>
        </>

        <SessionProvider>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
