CREATE TABLE "ekstra_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "ekstra_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "ekstra_app_image" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ekstra_app_image_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"url" varchar(1024) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "ekstra_creator_page" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"userId" varchar(255) NOT NULL,
	"pageUrl" varchar(1024) NOT NULL,
	"profileImage" varchar(255),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "ekstra_creator_page_pageUrl_unique" UNIQUE("pageUrl")
);
--> statement-breakpoint
CREATE TABLE "ekstra_membership_content" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"type" varchar(100) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "ekstra_membership" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"creatorId" varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"price" numeric(10, 2) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ekstra_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ekstra_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"role" varchar(50) DEFAULT 'user' NOT NULL,
	"image" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "ekstra_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "ekstra_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "ekstra_account" ADD CONSTRAINT "ekstra_account_userId_ekstra_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."ekstra_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ekstra_creator_page" ADD CONSTRAINT "ekstra_creator_page_userId_ekstra_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."ekstra_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ekstra_membership_content" ADD CONSTRAINT "ekstra_membership_content_createdById_ekstra_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."ekstra_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ekstra_membership" ADD CONSTRAINT "ekstra_membership_creatorId_ekstra_creator_page_id_fk" FOREIGN KEY ("creatorId") REFERENCES "public"."ekstra_creator_page"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ekstra_session" ADD CONSTRAINT "ekstra_session_userId_ekstra_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."ekstra_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "ekstra_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "imageName_idx" ON "ekstra_app_image" USING btree ("name");--> statement-breakpoint
CREATE INDEX "creator_page_user_idx" ON "ekstra_creator_page" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "creator_page_url_idx" ON "ekstra_creator_page" USING btree ("pageUrl");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "ekstra_membership_content" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "ekstra_membership_content" USING btree ("name");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "ekstra_session" USING btree ("userId");